"use client";

import PageWrapper from "@/components/PageWrapper";
import PageHeader from "@/components/PageHeader";
import Link from "next/link";

export default function AIVideoDetectorCaseStudyPage() {
  return (
    <PageWrapper>
      <PageHeader
        label="Case Study"
        title="AI Video Reality Detector"
        description="A deep learning system designed to detect whether a video is AI-generated or real."
      />

      {/* Sticky Back Button */}
      <div className="sticky top-24 z-40">
        <div className="max-w-4xl mx-auto px-4">
          <Link
            href="/projects"
            className="inline-flex items-center gap-2 rounded-full border
                       bg-white/80 dark:bg-neutral-900/80 backdrop-blur
                       px-4 py-2 text-sm font-medium
                       text-gray-700 dark:text-gray-300
                       hover:text-black dark:hover:text-white
                       hover:bg-white dark:hover:bg-neutral-800
                       transition shadow-sm"
          >
            ← Back to Projects
          </Link>
        </div>
      </div>

      {/* Case Study Content */}
      <div className="max-w-4xl mx-auto mt-12 space-y-12 text-muted-foreground leading-relaxed">

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Project Overview
          </h2>
          <p className="mt-3">
            The AI Video Reality Detector is a computer vision and deep learning
            system that analyzes video content to determine whether it was
            generated by AI or recorded from real-world footage.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Problem Statement
          </h2>
          <p className="mt-3">
            AI-generated videos are increasingly realistic, making manual
            verification unreliable. There is a growing need for automated tools
            capable of detecting synthetic video content at scale.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Goals & Objectives
          </h2>
          <ul className="mt-3 list-disc ml-6 space-y-2">
            <li>Detect AI-generated vs real videos</li>
            <li>Build a scalable video analysis pipeline</li>
            <li>Maintain accuracy across varying video quality</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Solution Design
          </h2>
          <p className="mt-3">
            The system processes videos through a structured pipeline involving
            frame extraction, preprocessing, feature analysis, and deep learning
            classification using pretrained models.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Technology Stack
          </h2>
          <ul className="mt-3 list-disc ml-6 space-y-2">
            <li>Python</li>
            <li>OpenCV for video processing</li>
            <li>HuggingFace pretrained models</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Challenges & Solutions
          </h2>
          <ul className="mt-3 space-y-3">
            <li>
              <strong>Dataset Variability:</strong> Solved through normalization
              and consistent preprocessing.
            </li>
            <li>
              <strong>Model Generalization:</strong> Improved using diverse
              datasets and evaluation across unseen samples.
            </li>
            <li>
              <strong>Computational Cost:</strong> Reduced using selective frame
              sampling.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Current Status
          </h2>
          <p className="mt-3">
            The project is currently in development, focusing on improving model
            accuracy and building a web-based interface for real-time detection.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-black dark:text-white">
            Key Learnings
          </h2>
          <ul className="mt-3 list-disc ml-6 space-y-2">
            <li>Data quality has a major impact on model accuracy</li>
            <li>Deepfake detection is an evolving technical challenge</li>
            <li>Efficient pipelines are essential for video processing</li>
          </ul>
        </section>

      </div>
    </PageWrapper>
  );
}
